digipay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('accounts.urls')),
    path('account/',include('bankaccounts.urls')),
    path('transfer/',include('transactions.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from transactions import transfer,payment_request,credit_card

app_name = 'transaction'

urlpatterns = [
    path('',transfer.search_user_by_acc_num,name='search'),
    path('amount_transfer/<account_number>/',transfer.amount_transfer,name='amount_transfer'),
    path('amount_transfer_process/<account_number>/', transfer.amount_transfer_process, name='amount_transfer_process'),
    path('transfer_confirmation/<account_number>/<transaction_id>/', transfer.transfer_confirmation, name='transfer_confirmation'),
    path('transfer_process/<account_number>/<transaction_id>/', transfer.transfer_process, name='transfer_process'),
    path('transfer_completed/<account_number>/<transaction_id>/',transfer.transfer_completed,name="transfer_completed"),
    path('transaction_details/<transaction_id>/',transfer.transaction_details,name="transaction_details"),
    path('user_request_payment/',payment_request.payment_request,name='payment_request'),
    path('payment_amount/<account_number>/',payment_request.request_amount,name="payment_amount"),
    path('request_amount_confirmation/<account_number>/<transaction_id>/',payment_request.request_amount_confirmation,name="request_amount_confirmation"),
    path('request_confirmation_success/<account_number>/<transaction_id>/',payment_request.request_confirmation_success,name='request_confirmation_success'),
    path('request_amount_final_process/<account_number>/<transaction_id>/,',payment_request.request_amount_final_process,name='request_amount_final_process'),
    path('send_confirmation/<account_number>/',payment_request.send_confirmation,name='send_confirmation'),
    path('send_completed/<account_number>/<transaction_id>/',payment_request.send_completed,name='send_completed'),
    path('credit_card/<number>/',credit_card.credit_card,name='credit_card'),
    path('credit_card_bill/<card_id>/',credit_card.credit_card_bill,name='credit_card_bill'),
    path('withdraw_amount/<card_id>/',credit_card.withdraw_amount,name='withdraw_amount'),
    path('credit_card_delete/<card_id>/',credit_card.credit_card_delete,name='credit_card_delete'),
    
]

templates/payment_request/request_amount.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">

                    <div class="choose-recipient">
                        <div class="step-area">
                            <h5>Request Amount</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="send-banance"> 
                            <span class="mdr">Amount</span>
                            <div class="input-area">
                                <input class="xxlr"  placeholder="" type="number" name="amount-send" id="amount-send">
                            </div>
                        
                        </div>
                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Description</span>
                            <div class="input-area">
                                <input class="xxlr"  type="text" name="description">
                                
                            </div>
                        </div>
                        <div class="footer-area mt-40">
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    {% endblock content %}

templates/payment_request/request_confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request amount</h4>
                    </div>

                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                        
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>You Send</span>
                                        <b>{{transaction.amount }}</b>
                                    </li>
                                    <li>
                                        <span>Recipient gets</span>
                                        <b>{{transaction.amount }}</b>
                                    </li>
                                    <li>
                                        <span>E-mail </span>
                                        <b>{{ account.user.email }}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Description</span>
                                        <b>{{ transaction.description }}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{ transaction.date }}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
         
                        <div class="footer-area mt-40">
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Confirm</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
    
    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab"
                                        data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer"
                                        aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab"
                                        data-bs-target="#success" type="button" role="tab" aria-controls="success"
                                        aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Enter your pin number below.</p>
                                            <form action="{% url 'transaction:request_amount_final_process' account.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>
                                                <a href="javascript:void(0)">Reset Pin Number?</a>
                                                <input type="submit" class="btn btn-primary" value="Confirm">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->
{% endblock content %}

templates/payment_request/request_confirmation_success.html
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div align="center">
        <form action="">
            <img src="" alt="">
            <p style="font-size: 30px;">
                Request 
                {{transaction.transaction_id }} is sent successfully to  {{ request.user }}</p>
            <button type="submit">Dashboard</button>
        </form>
    </div>

</body>
</html>

templates/payment_request/send_amount_completed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Payment Success</h1>
    <h1>{{transaction.sender}} sent amount of Rs.{{transaction.amount}} to {{transaction.receiver}} successfully. </h1>

</body>
</html>

templates/payment_request/send_completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Confirm Your Transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
    
                                    </div>
                                    <div class="text-area">
                                        <p>{{ request.user.account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ request.user.account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ request.user.account.user.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    
                                    <a href="#">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Payment Details</h6>
                            <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>Amount</span>
                                        <b>{{ transaction.amount }}</b>
                                    </li>
                                
                                    <li>
                                        <span>E-mail </span>
                                        <b>{{ account.user.email }}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Description</span>
                                        <b>{{ transaction.description }}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{ transaction.date }}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Confirm</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
    
    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab"
                                        data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer"
                                        aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab"
                                        data-bs-target="#success" type="button" role="tab" aria-controls="success"
                                        aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Enter your pin number below.</p>
                                            <form action="" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>
                                                <a href="javascript:void(0)">Reset Pin Number?</a>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->
{% endblock content %}

templates/payment_request/user_request_payment.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Search User</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                   
                    <form  class="flex-fill" method="POST">
                        {% csrf_token %}
                        <div class="form-group d-flex align-items-center">
                            <img src="{% static 'assets1/images/icon/search.png' %}" alt="icon">
                            <input type="text" name="account_number" placeholder="Enter Account Number or ID">
                            <button type="submit"><i class="fas fa-angle-right"></i></button>
                        </div>
                    </form>
                    <div class="user-select">
                        {% if query %} 
                        {% for a in account %}
                        <div class="single-user">
                            <div class="left d-flex align-items-center">
                                <div class="img-area">
                                    <img src="{{ a.user.kyc.image.url }}" style="width
                                    : 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">

                                </div>
                                <div class="text-area">
                                    <p>{{ a.user.kyc.full_name|title }}</p>
                                    <span class="mdr"><b>{{ a.account_number }}</b></span> <br>
                                    <span class="mdr">{{ a.user.email }}</span>
                                </div>
                            </div>
                            <div class="right">
                                <a href="{% url 'transaction:payment_amount' a.account_number %}">Request</a>
                            </div>
                        </div>
                        {% empty %}
                        <div>
                            <h4 class="mt-4">Account does not exist</h4>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Add Recipients Popup start -->
    <div class="add-recipients">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="recipientsMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header justify-content-between">
                                    <h6>Add Recipients</h6>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                </div>
                                <ul class="nav nav-tabs" role="tablist">
                                    <li class="nav-item" role="presentation">
                                        <button class="nav-link active" id="company-tab" data-bs-toggle="tab"
                                            data-bs-target="#company" type="button" role="tab" aria-controls="company"
                                            aria-selected="true">
                                            <span class="icon-area">
                                                <img src="{% static 'assets1/images/icon/company-icon.png' %}" alt="icon">
                                            </span>
                                            Company
                                        </button>
                                    </li>
                    
                                    </li>
                                </ul>
                    
                                                <div class="col-12">
                                                    <div class="btn-border w-100">
                                                        <button class="cmn-btn w-100">Add Recipients</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transactions Popup start -->
{% endblock content %}