digipay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('accounts.urls')),
    path('account/',include('bankaccounts.urls')),
    path('transfer/',include('transactions.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from transactions import transfer,payment_request,credit_card

app_name = 'transaction'

urlpatterns = [
    path('',transfer.search_user_by_acc_num,name='search'),
    path('amount_transfer/<account_number>/',transfer.amount_transfer,name='amount_transfer'),
    path('amount_transfer_process/<account_number>/', transfer.amount_transfer_process, name='amount_transfer_process'),
    path('transfer_confirmation/<account_number>/<transaction_id>/', transfer.transfer_confirmation, name='transfer_confirmation'),
    path('transfer_process/<account_number>/<transaction_id>/', transfer.transfer_process, name='transfer_process'),
    path('transfer_completed/<account_number>/<transaction_id>/',transfer.transfer_completed,name="transfer_completed"),
    path('transaction_details/<transaction_id>/',transfer.transaction_details,name="transaction_details"),
    path('user_request_payment/',payment_request.payment_request,name='payment_request'),
    path('payment_amount/<account_number>/',payment_request.request_amount,name="payment_amount"),
    path('request_amount_confirmation/<account_number>/<transaction_id>/',payment_request.request_amount_confirmation,name="request_amount_confirmation"),
    path('request_confirmation_success/<account_number>/<transaction_id>/',payment_request.request_confirmation_success,name='request_confirmation_success'),
    path('request_amount_final_process/<account_number>/<transaction_id>/,',payment_request.request_amount_final_process,name='request_amount_final_process'),
    path('send_confirmation/<account_number>/',payment_request.send_confirmation,name='send_confirmation'),
    path('send_completed/<account_number>/<transaction_id>/',payment_request.send_completed,name='send_completed'),
    path('credit_card/<number>/',credit_card.credit_card,name='credit_card'),
    path('credit_card_bill/<card_id>/',credit_card.credit_card_bill,name='credit_card_bill'),
    path('withdraw_amount/<card_id>/',credit_card.withdraw_amount,name='withdraw_amount'),
    path('credit_card_delete/<card_id>/',credit_card.credit_card_delete,name='credit_card_delete'),
    
]

transactions/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.contrib.auth.models import User
from bankaccounts.models import Account

# Create your models here.

TRANSACTION_STATUS = (
    ['failed','FAILED'],
    ['completed','COMPLETED'],
    ['pending','PENDING'],
    ['processing','PROCESSING'],
    ['request_sent','REQUEST_SENT'],
    ['request_processing','REQUEST_PROCESSING'],
)

TRANSACTION_TYPE = (
    ['transfer','TRANSFER'],
    ['withdraw','WITHDRAW'],
    ['refund','REFUND'],
    ['received','RECEIVED'],
    ['request','REQUEST'],
    ['none','NONE']
)

class Transaction(models.Model):
    transaction_id = ShortUUIDField(unique=True,length=15,max_length=20,prefix="TRN",alphabet="1234567890")
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name="user")
    amount = models.DecimalField(max_digits=10,decimal_places=2,default=0.00)
    description = models.CharField(max_length=1000,null=True,blank=True)
    receiver = models.ForeignKey(User, on_delete=models.SET_NULL,null=True,related_name="receiver")
    sender = models.ForeignKey(User, on_delete=models.SET_NULL,null=True,related_name="sender")
    receiver_account = models.ForeignKey(Account, on_delete=models.SET_NULL,null=True,related_name="receiver_account")
    sender_account = models.ForeignKey(Account, on_delete=models.SET_NULL,null=True,related_name="sender_account")
    status = models.CharField(max_length=100,choices=TRANSACTION_STATUS, default='pending')
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPE, default='none')
    date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now_add=False,null=True,blank=True) 

    def __str__(self):
        return f'{self.user}'
    
CARD_TYPE = (
    ['visa', 'VISA'],
    ['rupay','RUPAY'],
    ['mastercard','MASTERCARD'],
    ['platinum','PLATINUM']
)

CARD_STATUS = (
    ['active','ACTIVE'],
    ['inactive','INACTIVE'],
)

class CreditCard(models.Model):
    card_id = ShortUUIDField(unique=True,length=10, max_length=20,prefix="CRED",alphabet='1234567890') 
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=255)
    number = ShortUUIDField(unique=True,length=16,max_length=16,alphabet="1234567890")
    month = models.CharField(max_length=15)  
    year = models.IntegerField()
    CVV = ShortUUIDField(length=3,max_length=6, unique=True,alphabet='1234567890') 
    card_type = models.CharField(max_length=20,choices=CARD_TYPE)
    card_status = models.CharField(max_length=20,choices=CARD_STATUS,default='in_active')
    date = models.DateField(auto_now_add=True)
    amount = models.DecimalField(max_digits=10,decimal_places=2,default=0.00)
    
    def _str_(self):
        return f'{self.user}'

    

transactions/forms.py
from django import forms
from transactions.models import CreditCard

# class AccountSearchForm(forms.Form):
#     account_number = forms.CharField(label='Account Number', max_length=50)

class CreditCardForm(forms.ModelForm):
    
    class Meta:
        model = CreditCard
        fields = ['name','number','month', 'year', 'CVV','card_type']

templates/transactions/amount-transfer.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount of transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
    
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    
                                    <a href="#">
                                        <i class=""></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'transaction:amount_transfer_process' account.account_number %}" method="POST">
                        {% csrf_token %}
                        <div class="send-banance"> 
                            <span class="mdr">You Send</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="Rs.{{account.account_balance|intcomma}}" type="number" name="amount-send" id="amount-send">
                            </div>
                            <p>Available Balance<b>Rs.{{account.account_balance|intcomma}}</b></p>
                            <p id="new_balance"></p>
                            <p class="text-danger" id="error-div"></p>
                        </div>
                        <!-- Js -->

                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Payment Description</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="Payment for fees" type="text" name="description">
                                
                            </div>
                        </div>
                        <script>
                            function CalculateBalance(){
                                let available_balance = "{{ account.account_balance }}" // Get users current account balance 
                                let new_balance = document.getElementById("new_balance")
                                let sendAmount_input = document.getElementById("amount-send")
                                let sendAmount = sendAmount_input.value
                                let errorDiv = document.getElementById("error-div")
                                let total_to_pay = document.getElementById("total-to-pay")

                                let errors = []

                                new_bal = available_balance - sendAmount
                                console.log(new_bal);

                                //new_balance.innerHTML = `New Balance $${new_bal.toString().replace(/\B(?))}`
                                new_balance.innerHTML = `New Balance Rs. ${new_bal.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;
                                total_to_pay.innerHTML = `Rs ${sendAmount.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;

                                 if (new_bal < 0){
                                    new_balance.style.color = "red"
                                    alert("You can only send Rs." + available_balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","))
                                } else {
                                    new_balance.style.color = "#27276e"

                                }
                            
                            }
                        </script>
                        
                        <ul class="total-fees">
                            <li>Total Fees</li>
                            <li>Free</li>
                        </ul>
                        <ul class="total-fees pay">
                            <li><h5>Total To Pay</h5></li>
                            <li><h5 id="total-to-pay">Rs 0.00</h5></li>
                        </ul>
                        <div class="footer-area mt-40">
                            <a href="pay-step-1.html">Previous Step</a>
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    {% endblock content %}

templates/transactions/amount_transfer_process.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>processing</h1>
</body>
</html>

templates/transactions/transactions_details.html
{% extends "partials/dashboard-base.html" %}
{% block content %}
<style>
    .box1 {
        position: relative;
        left: 350px;
        top: 200px;
    }
</style>
    <div class="box1" id="transactions-table">
        <h4><b>Transactions :</b></h4>
        <button type="submit">Transfer</button> <button onclick="rec" type="submit">Received</button>
        <table border="1px solid black" cellpadding="10">
            <thead>
                <tr>
                    <th>Sender</th>
                    <th>Amount</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in request_receiver_transaction %}
                    <tr>
                        <td>{{ transaction.sender }}</td>
                        <td>{{ transaction.amount }}</td>
                        <td>{{ transaction.date }}</td>
                        <td>{{ transaction.status }}</td>
                        <td>
                            <form action="" method="post">
                                {% csrf_token %}
                                <button type="submit">Send</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                
                {% for transaction in request_sender_transaction %}
                <tr>
                    <td>{{ transaction.sender }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.date }}</td>
                    <td>{{ transaction.status }}</td>
                    <td>
                        <form action="" method="post">
                            {% csrf_token %}
                            <button type="submit">Send</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>            
    </div>
{% endblock %}

templates/transactions/transfer-completed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div align="center">
        <form action="#">
            <h1>Made a Payment</h1>
            <img src="" alt="">
            <p style="font-size: 30px;">
               <b>{{ request.user }}</b> ,Payment of {{transaction.amount }} amount is sent successfully. 
            </p>
            <button type="submit">Dashboard</button>
        </form>
    </div>

</body>
</html>

templates/transactions/transfer-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <!-- <img src="{{ a.user.kyc.image.url }}" alt="image"> -->
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">
    
                                    </div>
                                    <div class="text-area">
                                        <p>{{ request.user.account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ request.user.account.account_number }}</b></span> <br>
                                        <span class="mdr">{{ request.user.account.user.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    
                                    <a href="#">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Payment Details</h6>
                            <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>You Send</span>
                                        <b>{{transaction.amount }}</b>
                                    </li>
                                    <li>
                                        <span>Recipient gets</span>
                                        <b>{{transaction.amount }}</b>
                                    </li>
                                    <li>
                                        <span>E-mail </span>
                                        <b>{{ account.user.email }}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Description</span>
                                        <b>{{ transaction.description }}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{ transaction.date }}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="pay-step-2.html">Previous Step</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Pay</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
    
    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab"
                                        data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer"
                                        aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab"
                                        data-bs-target="#success" type="button" role="tab" aria-controls="success"
                                        aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Enter your pin number below.</p>
                                            <form action="{% url 'transaction:transfer_process' account.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="text">
                                                </div>
                                                <a href="javascript:void(0)">Reset Pin Number?</a>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->
{% endblock content %}